package contracts

// AjoGroupABI is the JSON ABI for the AjoGroup contract.
// Manually constructed to avoid an abigen dependency.
// Must stay in sync with contracts/src/AjoGroup.sol.
const AjoGroupABI = `[
  {
    "inputs":[{"internalType":"address","name":"_usdcToken","type":"address"}],
    "stateMutability":"nonpayable",
    "type":"constructor"
  },
  {
    "anonymous":false,
    "inputs":[
      {"indexed":true,"internalType":"uint256","name":"groupId","type":"uint256"},
      {"indexed":false,"internalType":"address[]","name":"members","type":"address[]"},
      {"indexed":false,"internalType":"uint256","name":"targetAmount","type":"uint256"},
      {"indexed":false,"internalType":"uint256","name":"deadline","type":"uint256"},
      {"indexed":false,"internalType":"address","name":"payoutAddress","type":"address"}
    ],
    "name":"GroupCreated",
    "type":"event"
  },
  {
    "anonymous":false,
    "inputs":[
      {"indexed":true,"internalType":"uint256","name":"groupId","type":"uint256"},
      {"indexed":true,"internalType":"address","name":"member","type":"address"},
      {"indexed":false,"internalType":"uint256","name":"amount","type":"uint256"},
      {"indexed":false,"internalType":"uint256","name":"totalContributed","type":"uint256"}
    ],
    "name":"Contributed",
    "type":"event"
  },
  {
    "anonymous":false,
    "inputs":[
      {"indexed":true,"internalType":"uint256","name":"groupId","type":"uint256"},
      {"indexed":false,"internalType":"uint256","name":"totalAmount","type":"uint256"},
      {"indexed":false,"internalType":"address","name":"payoutAddress","type":"address"}
    ],
    "name":"Released",
    "type":"event"
  },
  {
    "anonymous":false,
    "inputs":[
      {"indexed":true,"internalType":"uint256","name":"groupId","type":"uint256"},
      {"indexed":true,"internalType":"address","name":"member","type":"address"},
      {"indexed":false,"internalType":"uint256","name":"amount","type":"uint256"}
    ],
    "name":"Refunded",
    "type":"event"
  },
  {
    "inputs":[
      {"internalType":"address[]","name":"_members","type":"address[]"},
      {"internalType":"uint256","name":"_targetAmount","type":"uint256"},
      {"internalType":"uint256","name":"_deadline","type":"uint256"},
      {"internalType":"address","name":"_payoutAddress","type":"address"}
    ],
    "name":"createGroup",
    "outputs":[{"internalType":"uint256","name":"groupId","type":"uint256"}],
    "stateMutability":"nonpayable",
    "type":"function"
  },
  {
    "inputs":[
      {"internalType":"uint256","name":"groupId","type":"uint256"},
      {"internalType":"uint256","name":"amount","type":"uint256"}
    ],
    "name":"contribute",
    "outputs":[],
    "stateMutability":"nonpayable",
    "type":"function"
  },
  {
    "inputs":[{"internalType":"uint256","name":"groupId","type":"uint256"}],
    "name":"releaseFunds",
    "outputs":[],
    "stateMutability":"nonpayable",
    "type":"function"
  },
  {
    "inputs":[{"internalType":"uint256","name":"groupId","type":"uint256"}],
    "name":"refund",
    "outputs":[],
    "stateMutability":"nonpayable",
    "type":"function"
  },
  {
    "inputs":[{"internalType":"uint256","name":"groupId","type":"uint256"}],
    "name":"getGroup",
    "outputs":[
      {"internalType":"address[]","name":"members","type":"address[]"},
      {"internalType":"uint256","name":"targetAmount","type":"uint256"},
      {"internalType":"uint256","name":"deadline","type":"uint256"},
      {"internalType":"address","name":"payoutAddress","type":"address"},
      {"internalType":"uint256","name":"totalContributed","type":"uint256"},
      {"internalType":"bool","name":"released","type":"bool"}
    ],
    "stateMutability":"view",
    "type":"function"
  },
  {
    "inputs":[
      {"internalType":"uint256","name":"groupId","type":"uint256"},
      {"internalType":"address","name":"member","type":"address"}
    ],
    "name":"getContribution",
    "outputs":[{"internalType":"uint256","name":"","type":"uint256"}],
    "stateMutability":"view",
    "type":"function"
  },
  {
    "inputs":[],
    "name":"usdcToken",
    "outputs":[{"internalType":"address","name":"","type":"address"}],
    "stateMutability":"view",
    "type":"function"
  },
  {
    "inputs":[],
    "name":"groupCount",
    "outputs":[{"internalType":"uint256","name":"","type":"uint256"}],
    "stateMutability":"view",
    "type":"function"
  },
  {
    "inputs":[
      {"internalType":"uint256","name":"","type":"uint256"},
      {"internalType":"address","name":"","type":"address"}
    ],
    "name":"contributions",
    "outputs":[{"internalType":"uint256","name":"","type":"uint256"}],
    "stateMutability":"view",
    "type":"function"
  },
  {
    "inputs":[
      {"internalType":"uint256","name":"","type":"uint256"},
      {"internalType":"address","name":"","type":"address"}
    ],
    "name":"isMember",
    "outputs":[{"internalType":"bool","name":"","type":"bool"}],
    "stateMutability":"view",
    "type":"function"
  }
]`

// ERC20ABI is a minimal ERC20 ABI for the USDC approve/balanceOf calls.
const ERC20ABI = `[
  {
    "inputs":[
      {"internalType":"address","name":"spender","type":"address"},
      {"internalType":"uint256","name":"amount","type":"uint256"}
    ],
    "name":"approve",
    "outputs":[{"internalType":"bool","name":"","type":"bool"}],
    "stateMutability":"nonpayable",
    "type":"function"
  },
  {
    "inputs":[{"internalType":"address","name":"account","type":"address"}],
    "name":"balanceOf",
    "outputs":[{"internalType":"uint256","name":"","type":"uint256"}],
    "stateMutability":"view",
    "type":"function"
  },
  {
    "inputs":[],
    "name":"decimals",
    "outputs":[{"internalType":"uint8","name":"","type":"uint8"}],
    "stateMutability":"view",
    "type":"function"
  }
]`
